// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/timwmillard/fishing (interfaces: CompetitorRepo)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	fishing "github.com/timwmillard/fishing"
)

// CompetitorRepo is a mock of CompetitorRepo interface.
type CompetitorRepo struct {
	ctrl     *gomock.Controller
	recorder *CompetitorRepoMockRecorder
}

// CompetitorRepoMockRecorder is the mock recorder for CompetitorRepo.
type CompetitorRepoMockRecorder struct {
	mock *CompetitorRepo
}

// NewCompetitorRepo creates a new mock instance.
func NewCompetitorRepo(ctrl *gomock.Controller) *CompetitorRepo {
	mock := &CompetitorRepo{ctrl: ctrl}
	mock.recorder = &CompetitorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CompetitorRepo) EXPECT() *CompetitorRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *CompetitorRepo) Create(arg0 context.Context, arg1 fishing.Competitor) (fishing.Competitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(fishing.Competitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *CompetitorRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*CompetitorRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *CompetitorRepo) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *CompetitorRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*CompetitorRepo)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *CompetitorRepo) Get(arg0 context.Context, arg1 uuid.UUID) (fishing.Competitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(fishing.Competitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *CompetitorRepoMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*CompetitorRepo)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *CompetitorRepo) List(arg0 context.Context) ([]fishing.Competitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]fishing.Competitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *CompetitorRepoMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*CompetitorRepo)(nil).List), arg0)
}

// Update mocks base method.
func (m *CompetitorRepo) Update(arg0 context.Context, arg1 fishing.Competitor) (fishing.Competitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(fishing.Competitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *CompetitorRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*CompetitorRepo)(nil).Update), arg0, arg1)
}
