// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"github.com/google/uuid"
)

type FishingCompetitor struct {
	ID           int64
	CompetitorNo string
	FirstName    string
	LastName     string
	Email        string
	Address1     string
	Address2     string
	Suburb       string
	State        string
	Postcode     string
	Mobile       string
	EventID      uuid.UUID
}
