
DROP TABLE IF EXISTS  competitions;

DROP TABLE IF EXISTS  events;

DROP TABLE IF EXISTS  team;

DROP TABLE IF EXISTS  competitors;

DROP TABLE IF EXISTS  catches;

DROP TABLE IF EXISTS  species;

DROP TABLE IF EXISTS  users;

DROP TABLE IF EXISTS  tickets;

DROP TABLE IF EXISTS  clubs;

DROP TABLE IF EXISTS  organisation_users;