
DROP TABLE IF EXISTS  fishing.competitor CASCADE;
DROP TABLE IF EXISTS  fishing.event CASCADE;
DROP TABLE IF EXISTS  fishing.club CASCADE;
DROP TABLE IF EXISTS  fishing.team CASCADE;
DROP TABLE IF EXISTS  fishing.species CASCADE;
DROP TABLE IF EXISTS  fishing.catch CASCADE;

-- DROP TABLE IF EXISTS  users;

DROP SCHEMA IF EXISTS fishing;
