// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Competitor struct {
	ID           uuid.UUID
	EventID      uuid.UUID
	CompetitorNo sql.NullString
	Firstname    string
	Lastname     string
	Email        string
	Address1     string
	Address2     string
	Suburb       string
	State        string
	Postcode     string
	Phone        string
	Mobile       string
	Paid         int16
}
