// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCompetitor(ctx context.Context, arg CreateCompetitorParams) (FishingCompetitor, error)
	DeleteCompetitor(ctx context.Context, id uuid.UUID) (int64, error)
	GetCompetitor(ctx context.Context, id uuid.UUID) (FishingCompetitor, error)
	ListCompetitors(ctx context.Context) ([]FishingCompetitor, error)
	UpdateCompetitor(ctx context.Context, arg UpdateCompetitorParams) (FishingCompetitor, error)
}

var _ Querier = (*Queries)(nil)
